### ISSUE TITLE
Cannot find module '@glimmer/component/package.json' after upgrade to 1.0.2

### ISSUE THREAD

**Issue by beastmst** [JFTechnology/ember-keycloak-auth#27]
when updated from version 0.10.3 to 1.0.2

give me this problem
Cannot find module '@glimmer/component/package.json' in  @jftechnology/ember-keycloak-auth
